name: Python application  # Nome do workflow

on: [push]  # Define que o workflow será acionado em um push

jobs:
  build:
    runs-on: ubuntu-latest  # Define o ambiente de execução

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2  # Faz o checkout do código do repositório

    - name: Set up Python
      uses: actions/setup-python@v2  # Configura o Python
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala as dependências listadas no requirements.txt

    - name: Run tests
      run: |
        pytest  # Executa os testes com pytest